### PR TITLE
Fix #133

### LINKED ISSUE #133: UnicodeError in parler_tags
We get this error specially when BINGbot visits us, so it's not that it happens all the time, yet it triggers quite a lot of 500 errors. Any ideas?

```python
UnicodeDecodeError at /ru/xxxxxx/
'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)
Request Method:	GET
Request URL:	https://www.xxxxx.com/ru/xxxxx/?search_term=%C3%90%C5%B8%C3%91%E2%82%AC%C3%90%C2%BE%C3%91%E2%80%9E%C3%90%C2%B8%C3%90%C2%BB%C3%90%C2%B0%C3%90%C2%BA%C3%91%E2%80%9A%C3%90%C2%B8%C3%90%C2%BA%C3%90%C2%B0&specialty_id=20
Django Version:	1.8.11
Exception Type:	UnicodeDecodeError
Exception Value:	
'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)
Exception Location:	/XXXXX/site-packages/parler/templatetags/parler_tags.py in _url_qs, line 168
```

### PR DESCRIPTION
**Pull request by yakky**
Forces unicode on ``_url_qs`` output

Fix #133

### CODE REVIEW

**Comment by yakky** [comment]
@vdboor any specific reason for the previous syntax?

**Comment by vdboor** [comment]
@yakky : I'm not sure why I wrote it like that. The comment reveals a hint (# Leaving original encoding of str/unicode as is.) so I likely didn't want to touch or interfere with the chosen string type, and return it like it was given.

do you think the `force_text()` is needed there? Perhaps you're perfectly served by `u'{0}?{1}'.format(..)` too,

**Comment by yakky** [comment]
@vdboor IIRC python 3.2 does not support ``u'..`` syntax :/

**Comment by vdboor** [comment]
You're completely right about that. Let's leave it with `force_text()` then, and this can be removed after 3.2 support is dropped.

**Comment by vdboor** [comment]
@yakky I'm ready to release 1.6.3. Are you fine with that too? There is also a minor security fix there that I didn't disclose yet. Perhaps discuss this on #django-parler?

**Pull request merged**
