### PR TITLE
Fix AttributeError: 'ManyToOneRel' object has no attribute 'get_attname'

### LINKED ISSUE #131: AttributeError: 'ManyToOneRel' object has no attribute 'get_attname'
This is in fact part of the problem for #129. When I have Some model which is related to Translation and not to Master then this error occurs.

    AttributeError: 'ManyToOneRel' object has no attribute 'get_attname'

Making it possible to access relations to translation instead of master is hard, but for now not preventing creation of objects with other fields is a start.

I'm preparing a pull request for this.

### PR DESCRIPTION
**Pull request by vstoykov**
Fixes #131

### CODE REVIEW

**Comment by yakky** [comment]
@vstoykov nice! assigning to myself for review

**Comment by vstoykov** [comment]
@yakky Now I'm looking at this and I'm wondering if this will broke the check for `ForeingKeys` in the translation model to other models. I need to check this.

**Comment by vstoykov** [comment]
@yakky I updated my PR now with corrected logic for `ForeignKeys` and `ManyToManyFields`.

Affected are only Django versions >= 1.8 because from 1.8 Django change the `Model._meta` API and now `Model._meta.get_fields()` returns all fields and related managers which where not returned from `Model._meta.get_fields_with_model()` in older versions of Django.

**Comment by vdboor** [comment]
@vstoykov: great work, and thanks for adding the tests too! @yakky: do you think this can be merged?

**Comment by yakky** [comment]
It looks good but if it's in for you I'd like to check more throughfully. I'll do by tomorrow

**Comment by yakky** [comment]
@vstoykov @vdboor LGTM, merging

**Pull request merged**
