### PR TITLE
Update cache to use new 'fallbacks' dict value

### PR DESCRIPTION
**Pull request by jmelett**
Update `cache.py` to use the new introduced `fallbacks` keyword (instead of `fallback`)

### CODE REVIEW

**Comment by Chive** [comment]
``lang_dict['fallbacks']`` is actually a list so that's not gonna work. Will discuss with @jmelett directly and push another commit soon @vdboor

**Comment by Chive** [comment]
@vdboor ready for check in /cc @jmelett

**Comment by Chive** [comment]
@vdboor ready for check in /cc @jmelett

**Comment by mikek** [comment]
I'll just reference related bug #82 here.

**Comment by vdboor** [comment]
Thanks for looking into this! Sorry for my late reply. I happen to miss GitHub notifications one in a while :(

**Comment by vdboor** [comment]
Just wondering, if language is in the fallback_languages, do you think the code should "resume" at the next? e.g.

```
try:
    start = lang_dict['fallbacks'].index(language_code)
except ValueError:
    start = 0
for fallback_lang in lang_dict['fallbacks'][start:]:
    return ...
```

**Pull request merged**
